//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace NascoWebAPI.Data
{
    [Table("Area")]
    public partial class Area
    {
        public int Id { get; set; }
        public string AreaCode { get; set; }
        public string AreaName { get; set; }
        public Nullable<bool> IsPublic { get; set; }
        public int State { get; set; }
        public Nullable<int> CenterId { get; set; }
    }
}
