//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace NascoWebAPI.Data
{
    [Table("CouponLading")]
    public partial class CouponLading
    {
        public int Id { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public int? State { get; set; }
        public int? LadingId { get; set; }
        public int? CouponId { get; set; }
        public double? DiscountAmount { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<int> UnapprovedTimes { get; set; }
        public string Note { get; set; }
        public Nullable<int> Status { get; set; }
        [ForeignKey("CouponId"), DatabaseGenerated(DatabaseGeneratedOption.None)]
        public virtual Coupon Coupon { get; set; }
    }
}