//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace NascoWebAPI.Data
{
    [Table("CouponOfficer")]
    public partial class CouponOfficer
    {
        public int Id { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public int? State { get; set; }
        public int? UserId { get; set; }
        public int? UserAssignedId { get; set; }
        public int? CouponId { get; set; }
        public int? NumberUses { get; set; }
        [ForeignKey("CouponId"), DatabaseGenerated(DatabaseGeneratedOption.None)]
        public virtual Coupon Coupon { get; set; }
    }
}