//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace NascoWebAPI.Data
{
    [Table("Customer")]
    public partial class Customer
    {
        public int CustomerID { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string Adress_CT { get; set; }
        public string CompanyName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public string Lat { get; set; }
        public string Address { get; set; }
        public string Lng { get; set; }
        public string Account_Number { get; set; }
        public string Tax_Code { get; set; }
        public Nullable<int> Business_OfficeId { get; set; }
        public Nullable<int> Officer_Liabilities { get; set; }
        public Nullable<int> Officer_ServiceId { get; set; }
        public Nullable<int> Officer_PostmanId { get; set; }
        public Nullable<int> PostOffice_Id { get; set; }
        public Nullable<int> Create_By { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<bool> IsAllowAccept { get; set; }
        public Nullable<int> PriceListID { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> CityId { get; set; }
        public string InstanceIDToken { get; set; }
        public string AddressNote { get; set; }
        public string PriceListIds { get; set; }
    }
}
