//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace NascoWebAPI.Data
{
    [Table("CustomerContact")]
    public partial class CustomerContact
    {
        public int Id { get; set; }
        public int? CreatedBy { get; set; }
        public System.DateTime? CreatedDate { get; set; }
        public int? ModifiedBy { get; set; }
        public System.DateTime? ModifiedDate { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        public string ContactAddress { get; set; }
        public string ContactEmail { get; set; }
        public int? CustomerId { get; set; }
        public int? State { get; set; }
        public string Note { get; set; }
        public string ContactIdentity { get; set; }
        public string Code { get; set; }
        public double? Lat { get; set; }
        public double? Lng { get; set; }
        public int? CityId { get; set; }
        public int? DistrictId { get; set; }
        public int? CountryId { get; set; }
    }
}
