//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace NascoWebAPI.Data
{
    [Table("DividendOfVolumetricWeight")]
    public partial class DividendOfVolumetricWeight
    {
        public int Id { get; set; }
        public Nullable<int> Dividend { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Default { get; set; }
    }
}
