
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace NascoWebAPI.Data
{
    [Table("Flight")]
    public partial class Flight
    {
        public int Id { get; set; }
        public string FlightCode { get; set; }
        public string FlightMAWB { get; set; }
        public Nullable<int> FlightStatus { get; set; }
        public Nullable<int> POFrom { get; set; }
        public Nullable<int> POTo { get; set; }
        public Nullable<int> DepartmentTo { get; set; }
        public Nullable<System.DateTime> Date_Create { get; set; }
        public string Note { get; set; }
        public string ListPackage { get; set; }
        public Nullable<double> TotalWeight { get; set; }
        public Nullable<double> TotalWeightExchange { get; set; }
        public Nullable<int> TotalPackage { get; set; }
        public Nullable<int> Create_By { get; set; }
        public Nullable<int> MAWBId { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<double> TotalWeightToPrice { get; set; }
        [ForeignKey("MAWBId"), DatabaseGenerated(DatabaseGeneratedOption.None)]
        public MAWB MAWB { get; set; }
        [ForeignKey("FlightStatus"), DatabaseGenerated(DatabaseGeneratedOption.None)]
        public Status Status { get; set; }
        [ForeignKey("POFrom"), DatabaseGenerated(DatabaseGeneratedOption.None)]
        public PostOffice PostOfficeFrom { get; set; }
        [ForeignKey("POTo"), DatabaseGenerated(DatabaseGeneratedOption.None)]
        public PostOffice PostOfficeTo { get; set; }
    }
}

