//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace NascoWebAPI.Data
{
    [Table("Job")]
    public partial class Job
    {
        public int Id { get; set; }
        public string JobTitle { get; set; }
        public Nullable<double> SalaryMax { get; set; }
        public Nullable<double> SalaryMin { get; set; }
        public string JobCode { get; set; }
    }
}
