//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace NascoWebAPI.Data
{
    [Table("Location")]
    public partial class Location
    {
        //public Location()
        //{
        //    this.LadingRecipients = new HashSet<Lading>();
        //    this.LadingSends = new HashSet<Lading>();
        //}
        public int LocationId { get; set; }
        public Nullable<int> Location_area_Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> State { get; set; }
        public string Code_Local { get; set; }
        public Nullable<int> Arrangement { get; set; }
        public Nullable<int> PostOfficeId { get; set; }
        public string ShortName { get; set; }
        public int? DistrictTypeId { get; set; }
        //[NotMapped]
        //public virtual ICollection<Lading> LadingRecipients { get; set; }
        //[NotMapped]
        //public virtual ICollection<Lading> LadingSends { get; set; }


    }
}
