//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace NascoWebAPI.Data
{
    [Table("Officer")]
    public partial class Officer
    {
        public int OfficerID { get; set; }
        public System.Guid GuiId { get; set; }
        public string Avatar { get; set; }
        public string OfficerName { get; set; }
        public Nullable<int> DeparmentID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Identified { get; set; }
        public string Lat { get; set; }
        public string Lng { get; set; }
        public string Phone { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<bool> StateOnline { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public Nullable<int> Types { get; set; }
        public Nullable<System.DateTime> LocationTime { get; set; }
        public string LatDynamic { get; set; }
        public string LngDynamic { get; set; }
        public string InstanceIDToken { get; set; }
        public Nullable<int> PostOfficeId { get; set; }
        public string InstanceIDTokenFromWeb { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string BankAccountNumber { get; set; }
        public Nullable<int> JobId { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedWhen { get; set; }
        [ForeignKey("PostOfficeId"), DatabaseGenerated(DatabaseGeneratedOption.None)]
        public virtual PostOffice PostOffice { get; set; }
    }
}
