//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace NascoWebAPI.Data
{
    [Table("PriceServiceOther")]
    public partial class PriceServiceOther
    {
        public int Id { get; set; }
        public string ServiceOtherCode { get; set; }
        public Nullable<int> GroupServiceId { get; set; }
        public Nullable<double> WeightMax { get; set; }
        public Nullable<int> FormulaId { get; set; }
        public Nullable<double> Value { get; set; }
        public Nullable<bool> FormulaAbsolute { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Default { get; set; }
        public Nullable<int> PriceListId { get; set; }
    }
}
