//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace NascoWebAPI.Data
{
    [Table("PriceDetailCustomer")]
    public partial class PriceDetailCustomer
    {
        public int Id { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> PriceDetailId { get; set; }
        public Nullable<double> DiscountAmount { get; set; }
        public Nullable<bool> Fixed { get; set; }
        public Nullable<double> VP_VP_DiscountAmount { get; set; }
        public Nullable<double> VP_DC_DiscountAmount { get; set; }
        public Nullable<double> VP_SB_DiscountAmount { get; set; }
        public Nullable<double> DC_DC_DiscountAmount { get; set; }
        public Nullable<double> DC_VP_DiscountAmount { get; set; }
        public Nullable<double> DC_SB_DiscountAmount { get; set; }
        public Nullable<double> SB_SB_DiscountAmount { get; set; }
        public Nullable<double> SB_DC_DiscountAmount { get; set; }
        public Nullable<double> SB_VP_DiscountAmount { get; set; }
    }
}