//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace NascoWebAPI.Data
{
    [Table("Promotion")]
    public partial class Promotion
    {
        public int Id { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public int? State { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public Nullable<bool> IsPublic { get; set; }
        public Nullable<int> DiscountTypeId { get; set; }
        public Nullable<double> DiscountAmount { get; set; }
        public Nullable<bool> IsInternal { get; set; }
        public string Content { get; set; }
        public string Quote { get; set; }
        public string Title { get; set; }
        public Nullable<int> CouponLength { get; set; }
        public Nullable<int> CouponQuantity { get; set; }
        public Nullable<int> CouponPrefix { get; set; }
        public Nullable<int> CouponSuffix { get; set; }
        public Nullable<int> CouponFormatType { get; set; }
        public Nullable<bool> IsAutoGeneration { get; set; }
        public Nullable<int> UsesPerCoupon { get; set; }
        public Nullable<int> UsesPerUser { get; set; }
        public Nullable<int> NumberUses { get; set; }
    }
}