//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace NascoWebAPI.Data
{
    [Table("Recipient")]
    public partial class Recipient
    {
        //public Recipient()
        //{
        //    Ladings = new HashSet<Lading>();
        //}
        public int Id { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Phone2 { get; set; }
        public string Address { get; set; }
        public string AddressNote { get; set; }
        public int? CityId { get; set; }
        public int? DistrictId { get; set; }
        public double? Lat { get; set; }
        public double? Lng { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> State { get; set; }
        [ForeignKey("DistrictId"), DatabaseGenerated(DatabaseGeneratedOption.None)]
        public Location District { get; set; }
        [ForeignKey("CityId"), DatabaseGenerated(DatabaseGeneratedOption.None)]
        public Location City { get; set; }
    }
}
