//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace NascoWebAPI.Data
{
    [Table("ServiceOtherFormula")]
    public partial class ServiceOtherFormula
    {
        public int Id { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> StructureId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<int> CityFromId { get; set; }
        public Nullable<int> CityToId { get; set; }
        public Nullable<double> MoneyRange { get; set; }
        public Nullable<double> ChargeMin { get; set; }
        public Nullable<double> ChargeMax { get; set; }
        public string Formula { get; set; }
        public Nullable<int> ServiceOtherId { get; set; }
        public Nullable<int> DistrictTypeId { get; set; }
        public string ColumnNameMoneyRange { get; set; }
        public string Description { get; set; }
        public Nullable<int> PriceListId { get; set; }
    }
}
