//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace NascoWebAPI.Data
{
    [Table("Transport")]
    public partial class Transport
    {
        public int Id { get; set; }
        public string TransportCode { get; set; }
        public string TransportName { get; set; }
        public Nullable<bool> IsGlobal { get; set; }
        public Nullable<int> Index { get; set; }
    }
}
