//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace NascoWebAPI.Data
{
    [Table("SetupAddOn")]
    public partial class SetupAddOn
    {
        public int Id { get; set; }
        public string SAOCode { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<int> AOIdFrom { get; set; }
        public Nullable<int> AOIdTo { get; set; }
    }
}
