//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace NascoWebAPI.Data
{
    [Table("Structure")]
    public partial class Structure
    {
        public int Id { get; set; }
        public string StructureCode { get; set; }
        public string StructureName { get; set; }
        public Nullable<bool> IsHighValue { get; set; }
    }
}
