//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace NascoWebAPI.Data
{
    [Table("TimeLinePostOfficeLevel")]
    public partial class TimeLinePostOfficeLevel
    {
        public int Id { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> TimeLineId { get; set; }
        public Nullable<int> PostOfficeLevel { get; set; }
        public Nullable<System.TimeSpan> TimeStart { get; set; }
        public Nullable<int> IntervalTime { get; set; }
        public Nullable<System.TimeSpan> TimeEnd { get; set; }
        public Nullable<int> IntervalDay { get; set; }
        public string Code { get; set; }
    }
}
