//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace NascoWebAPI.Data
{
    [Table("BB_View_ServiceOtherPriceList")]
    public partial class BB_View_ServiceOtherPriceList
    {
        public int ID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public Nullable<double> Money { get; set; }
        public string Description { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> PriceListID { get; set; }
        public Nullable<int> FormulaID { get; set; }
        public string PriceListName { get; set; }
        public string FormulaName { get; set; }
        public string ServiceName { get; set; }
        public string ServiceCode { get; set; }
    }
}
