//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace NascoWebAPI.Data
{
    [Table("BB_View_Calculator")]
    public partial class BB_View_Calculator
    {
        public int Id { get; set; }
        public Nullable<int> LocaitionId { get; set; }
        public Nullable<int> LocationType { get; set; }
        public Nullable<double> WeightMax { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> PostOfficeId { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Formula { get; set; }
        public Nullable<int> PriceListID { get; set; }
        public string ColumnName { get; set; }
        public Nullable<int> PriceID { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<bool> IsFly { get; set; }
        public Nullable<int> TransportID { get; set; }
        public Nullable<bool> IsPlus { get; set; }
    }
}
